### ISSUE TITLE
Credit on 2019-001.md

### ISSUE THREAD

**Issue by konradwilk** [Netflix/security-bulletins#2]
The page says: "We thank Jonathan Lemon and Alexey Kodanev for helping to improve the Linux patches."

Please amend that to:

"We thank Jonathan Lemon,. Alexey Kodanev and Joao Martins for helping to improve the Linux patches."

Alexey reported the bug. Joao found the solution.

Thank you!

**Comment by sbehrens** [comment]
Added, thanks!
