### ISSUE TITLE
ir-netflix-net

### ISSUE THREAD

**Issue by PRO-COINMARKETCAP** [Netflix/security-bulletins#23]
```

#ir-netflix-net

https://ir.netflix.net

```
Growth of $1,000,000.00 Investment: [0001065280](Daniel Bebjiman Leahy)

GROWTH WITHOUT DIVIDENDS REINVESTED

(in thousands)

NASDAQ:NFLX
2016
2018
2020
2022
0
2.5M
5M
7.5M
10M
Start Date
Jul 6, 2015
End Date
Jul 3, 2023
Start Price/Share
$94.57
End Price/Share
$441.44
Total Return
366.78%
Compound Annual Growth Rate
21.26%
Starting Investment
$1,000,000.00
Ending Investment
$4,667,795.97
Years
8

**Comment by orangetw** [comment]
請確認你的電子郵件地址

你的確認碼如下。請在開啟的瀏覽器視窗中輸入確認碼，我們就會協助你登入。

8BU-PFP

如果你並未請求傳送這封電子郵件，則無需擔心，你可以放心忽略這封信。
