### ISSUE TITLE
IPtables filter may be inefective due to placement

### ISSUE THREAD

**Issue by Darkbat91** [Netflix/security-bulletins#4]
I believe the IP tables rule should be updated with a top insert to ensure that the packet does not get accepted prior to the appended rule and that to further ensure no issues it should be added to the mangle table which is the lead of the stack. 

iptables -t mangle -I INPUT -p tcp -m tcpmss --mss 1:500 -j DROP

**Comment by SonOfSunTzu** [comment]
Heh, I decided to check the existing commits before submitting my own Pull Request on this ;)

I agree, using "-I" will ensure this is the first rule checked, rather than the last.
Otherwise the attack, AIUI, will be possible over connections that are already permitted, and for Internet facing servers this is probably connections to all their main services anyway...

**Comment by notr1ch** [comment]
Are these vulnerabilities specific to IPv4? If not, an equivalent `ip6tables` rule should probably be recommended too.

**Comment by Darkbat91** [comment]
@notr1ch  No one has stated that IPV6 is effected and due to the V6 space of 1220 octets where the V4 has only 536 octets i would not think it is impacted. I am sure someone could validate it though.

**Comment by mcbrutus** [comment]
Inserting the iptable rule at the front is a good idea and need to make sure that the table isn't reinitialized after elsewhere.

The IPv6 issue is unknown but adding an ip6table rule would be a good safety measure.

**Comment by h1z1** [comment]
Don't really want to create another ticket for this but on the subject of ineffective rules, can someone from Netflix _PLEASE_ make it very clear to casual people viewing that they need not rush out to every SOC demanding they implement this?   Having a low MSS does _not_ mean anything,   There are very valid reasons for having one unrelated to this issue.  

Thank you.

**Comment by tyit** [comment]
@notr1ch 

ip6tables -I INPUT -p tcp --tcp-flags SYN SYN -m tcpmss --mss 1： 500 -j DROP
