### ISSUE TITLE
PATCH_net_1_4.patch - Issue

### ISSUE THREAD

**Issue by senthilnathann** [Netflix/security-bulletins#9]
Hi ,

In PATCH_net_1_4.patch have 5 files modifications/changes.

net/ipv4/tcp_output.c modification lines are not available in following kernel version in Centos. 

Kernel versions :-
3.10.0-693.11.6.el7.x86_64
3.10.0-514.26.2.el7.x86_64
3.10.0-327.36.3.el7.x86_64

**Not available lines :**
```
@@ -2747,7 +2747,7 @@ static bool tcp_collapse_retrans(struct sock *sk, struct sk_buff *skb)
 		if (next_skb_size <= skb_availroom(skb))
 			skb_copy_bits(next_skb, 0, skb_put(skb, next_skb_size),
 				      next_skb_size);
-		else if (!skb_shift(skb, next_skb, next_skb_size))
+		else if (!tcp_skb_shift(skb, next_skb, 1, next_skb_size))
 			return false;
 	}
 	tcp_highest_sack_replace(sk, next_skb, skb);
```

Due to this kpatch got failed .Please check and do the needful.

Regards,
Senthil

**Comment by tsingliu** [comment]
My kernel version is 3.10.0-514.26.2.el7.x86_64，and kpatch-build failed。Check all of patch files  is "1 out of 1 hunk FAILED"

**Comment by senthilnathann** [comment]
Due to extra space and some other reasons hunk failures are happened .If we do the patches manually (include changes ) in particular source files ,then run kpatch-build .Hope it will resolve hunk failures .
But in my case , can't able to do the changes in have mentioned file.

**Comment by bobrik** [comment]
3.10 is an ancient kernel not supported by upstream anymore:

* https://www.openwall.com/lists/oss-security/2019/06/17/6

You have to ask your vendor for updates (or better yet upgrade your kernel to something supported).

**Comment by PaulMcMillan** [comment]
Unfortunately, we are unable to accept support requests here. Please address concerns to your upstream software provider.

**Comment by szepeviktor** [comment]
@PaulMcMillan Could you add this statement in the README?

**Comment by PaulMcMillan** [comment]
@szepeviktor sure, I've added that.
